spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

keycloak:
  admin:
    username: ${KEYCLOAK_USERNAME}
    password: ${KEYCLOAK_PASSWORD}
    server-url: ${KEYCLOAK_SERVER-URL}
    realm: ${KEYCLOAK_REALM}
    client-id: admin-cli

server:
  port: 5081
