management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/BankingProject

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${SERVER_PORT}
